services:
  portfolio:
    image: ghcr.io/v4ldum/portfolio:latest
    restart: unless-stopped
    networks:
      - "netv6"
    environment:
      - TZ=Europe/Paris
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.tls=true"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.rule=Host(`portfolio.valdum.dev`)"

networks:
  netv6:
    external: true