name: portfolio
description: 
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  static_shock: any
  yaml: ^3.1.3
  rust: ^3.1.0
  html: ^0.15.5+1

dev_dependencies:
  lints: ^2.0.0
