name: mock_bingo
description: 
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  bingo:
    git:
        url: https://github.com/V4ldum/bingo.git
        #ref: branch_name_or_commit_hash_or_tag

