name: pipeline
on:
    workflow_dispatch:
    push:
        branches:
            - "main"
        paths:
            - bin/**
            - source/**
            - docker-compose.yml
            - Dockerfile

permissions:
    contents: read
    packages: write

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    deploy:
        uses: V4ldum/shared-workflows/.github/workflows/pipeline-dart.yml@main
        with:
            project: "portfolio"
            run_tests: true
        secrets: inherit
