name: CI/CD
on:
    workflow_dispatch:
    #push:
    #    branches:
    #        - "main"
    #    paths:
    #        - lib/**
    #        - source/**
    #        - Dockerfile
    #        - docker-compose.yml

permissions:
    contents: read
    packages: write

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    detect-changes:
        runs-on: ubuntu-latest
        outputs:
            build: ${{ steps.filter.outputs.build }}
            deploy: ${{ steps.filter.outputs.deploy }}
        steps:
            - uses: actions/checkout@v7
            - uses: dorny/paths-filter@v4
              id: filter
              with:
                  filters: |
                      build:
                          - 'lib/**'
                          - 'source/**'
                          - 'Dockerfile'
                      deploy:
                          - 'docker-compose.yml'

    test:
        needs: detect-changes
        if: needs.detect-changes.outputs.build == 'true'
        uses: v4ldum/shared-workflows/.github/workflows/test-static-shock.yml@main
        with:
            enabled: true

    build:
        needs: test
        uses: v4ldum/shared-workflows/.github/workflows/build.yml@main
        secrets: inherit
        with:
            project: portfolio

    deploy:
        needs: [detect-changes, build]
        if: >-
            needs.build.result == 'success' ||
              needs.build.result == 'skipped' &&
              needs.detect-changes.outputs.deploy == 'true'
        uses: v4ldum/shared-workflows/.github/workflows/deploy.yml@main
        secrets: inherit

    cleanup:
        needs: [build, deploy]
        if: needs.build.result == 'success'
        uses: v4ldum/shared-workflows/.github/workflows/cleanup.yml@main
        secrets: inherit
        with:
            project: ${{ needs.detect-changes.outputs.project }}
