name: pipeline
on:
 push:
   branches:
     - "main"

permissions:
  contents: read
  packages: write

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1

      - name: Config Flutter
        run: dart --disable-analytics
          
      - name: Install dependencies
        run: dart pub get

      - name: Analyze project source
        run: dart analyze

  build-and-push-image:
    runs-on: ubuntu-24.04-arm
    needs:
      - run-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx # For cross-platform support
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: |
            ghcr.io/v4ldum/portfolio:latest
            ghcr.io/v4ldum/portfolio:${{ github.sha }}